language: c

before_script:
    - apt-get update -qq
    - apt-get install -y git make python gcc g++ python-pkgconfig libz-dev libglib2.0-dev dh-autoreconf libc6-dev-i386 wget unzip llvm libncurses5-dev clang
    - git submodule update --init --recursive
    - make prepare
    - make examples

script:
    - make all

after_script:
    - ./packer examples/opti
    - ./packer -t 48c7c034120000c3 examples/opti
